apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm
  # You'll usually want to add your resources to the argocd namespace.
  namespace: openshift-gitops
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

 

  # Source of the application manifests
  source:
    repoURL: https://github.com/marpears/gitops-demo.git
    targetRevision: HEAD
    path: ./infra/app-of-apps/hub-cluster/rhacm

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management

 

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
